FROM jenkins:2.46.1
USER root
RUN apt-get update
RUN apt-get install sshpass -y
ENV MAVEN_VERSION 3.3.9
COPY apache-maven-3.3.9-bin.tar.gz /
RUN tar -xzf /apache-maven-3.3.9-bin.tar.gz -C /usr/share 

#RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
#RUN mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven 
RUN ln -s /usr/share/apache-maven-$MAVEN_VERSION/bin/mvn /usr/bin/mvn
ADD settings.xml /usr/share/apache-maven-$MAVEN_VERSION/conf/settings.xml
RUN rm -fr /apache-maven-3.3.9-bin.tar.gz
ENV MAVEN_HOME /usr/share/apache-maven-$MAVEN_VERSION
VOLUME /root/.m2


